name: ghiras
description: "A beautiful and optimized Quranic application with offline support."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  adhan: ^2.0.0+1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  flutter_local_notifications: ^17.0.0
  get_it: ^7.6.7
  go_router: ^14.3.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  timezone: ^0.9.4
  uuid: ^4.3.3
  path_provider: ^2.1.2
  dio: ^5.7.0
  just_audio_background: ^0.0.1-beta.17
  fluttertoast: ^8.2.8
  animate_do: ^3.3.4
  fluttericon: ^2.0.0
  cached_network_image: ^3.4.1
  back_button_interceptor: ^7.0.1
  azlistview: ^2.0.0
  animations: ^2.0.11
  easy_container: ^1.0.4
  flutter_staggered_animations: ^1.1.1
  intl: ^0.19.0
  quran: 1.4.1
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  scrollable_positioned_list: ^0.2.3
  get: ^4.7.3
  screenshot: ^3.0.0
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  hijri: ^3.0.0
  share_plus: ^10.1.0
  perfect_volume_control: ^1.0.6
  flutter_compass_v2: ^1.0.0
  permission_handler: ^11.0.0
  flutter_colorpicker: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/audio/

  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf

    - family: Taha
      fonts:
        - asset: assets/fonts/taha.ttf

    - family: me
      fonts:
        - asset: assets/fonts/me_quran.ttf

    - family: UthmanicHafs13
      fonts:
        - asset: assets/fonts/UthmanicHafs1 Ver13.otf

    - family: qaloon
      fonts:
        - asset: assets/fonts/qaloon.ttf

    - family: pdsm
      fonts:
        - asset: assets/fonts/pdms.otf

    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

    - family: roboto
      fonts:
        - asset: assets/fonts/roboto.ttf

    - family: arsura
      fonts:
        - asset: assets/fonts/arsura.ttf

    - family: QCF_P001
      fonts:
        - asset: assets/fonts/v2woff/p1.ttf

    - family: QCF_P002
      fonts:
        - asset: assets/fonts/v2woff/p2.ttf

    - family: QCF_P003
      fonts:
        - asset: assets/fonts/v2woff/p3.ttf

    - family: QCF_P004
      fonts:
        - asset: assets/fonts/v2woff/p4.ttf

    - family: QCF_P005
      fonts:
        - asset: assets/fonts/v2woff/p5.ttf

    - family: QCF_P006
      fonts:
        - asset: assets/fonts/v2woff/p6.ttf

    - family: QCF_P007
      fonts:
        - asset: assets/fonts/v2woff/p7.ttf

    - family: QCF_P008
      fonts:
        - asset: assets/fonts/v2woff/p8.ttf

    - family: QCF_P009
      fonts:
        - asset: assets/fonts/v2woff/p9.ttf

    - family: QCF_P010
      fonts:
        - asset: assets/fonts/v2woff/p10.ttf

    - family: QCF_P011
      fonts:
        - asset: assets/fonts/v2woff/p11.ttf

    - family: QCF_P012
      fonts:
        - asset: assets/fonts/v2woff/p12.ttf

    - family: QCF_P013
      fonts:
        - asset: assets/fonts/v2woff/p13.ttf

    - family: QCF_P014
      fonts:
        - asset: assets/fonts/v2woff/p14.ttf

    - family: QCF_P015
      fonts:
        - asset: assets/fonts/v2woff/p15.ttf

    - family: QCF_P016
      fonts:
        - asset: assets/fonts/v2woff/p16.ttf

    - family: QCF_P017
      fonts:
        - asset: assets/fonts/v2woff/p17.ttf

    - family: QCF_P018
      fonts:
        - asset: assets/fonts/v2woff/p18.ttf

    - family: QCF_P019
      fonts:
        - asset: assets/fonts/v2woff/p19.ttf

    - family: QCF_P020
      fonts:
        - asset: assets/fonts/v2woff/p20.ttf
